name: "Setup Dependencies"
description: "Setup tools/dependencies"
inputs:
  install_task:
    description: "install task if true"
    default: "true"
  task_version:
    description: "version of task to install"
    default: "v3.44.0"

  install_terraform:
    description: "install terraform if true"
    default: "false"
  install_python:
    description: "install python if true"
    default: "false"
  service_path:
    description: "path to service within repo (used to find version file)"
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install go-task
      if: ${{ inputs.install_task == 'true' }}
      uses: supplypike/setup-bin@1fafb085795af4a3f183502f3a9dffa8f7b83217 # v5.0.0
      with:
        uri: "https://github.com/go-task/task/releases/download/${{ inputs.task_version }}/task_linux_amd64.tar.gz"
        name: task
        version: ${{ inputs.task_version }}

    - name: Set up Go
      if: ${{ inputs.install_terraform == 'true' }}
      uses: actions/setup-go@1d76b952eb9246b03e20e15a9ef98c6d4af389ef # v5.5.0
      with:
        go-version: '1.20'

    - name: Cache Go modules
      if: ${{ inputs.install_terraform == 'true' }}
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum','**/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get Go modules
      if: ${{ inputs.install_terraform == 'true' }}
      shell: bash
      run: |
        echo "GOMODCACHE: $(go env GOMODCACHE)"
        go mod download

    - name: Set up Python
      if: ${{ inputs.install_python == 'true' }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
        cache-dependency-path: ./${{ inputs.service_path }}/tests/requirements-tests.txt

    - name: Install dependencies
      if: ${{ inputs.install_python == 'true' }}
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ./${{ inputs.service_path }}/tests/requirements.txt
