---
skip-check:
  - CKV_DOCKER_2
  - CKV_DOCKER_7
  - CKV_AWS_355
  - CKV_AWS_158
  - CKV_AWS_338
  - CKV_AWS_290
  - CKV2_AWS_12
  - CKV_AWS_152
  - CKV_AWS_131
  - CKV_AWS_260
  - CKV_AWS_23
  - CKV_AWS_382
  - CKV_AWS_2
  - CKV2_AWS_20
  - CKV2_AWS_74
  - CKV_AWS_91
  - CKV_AWS_288
  - CKV_AWS_378
