---
skip-check:
  - CKV_AWS_136
  - CKV_AWS_355
  - CKV_AWS_378
  - CKV_AWS_290
  - CKV_AWS_338
  - CKV_AWS_158
  - CKV_AWS_382
  - CKV_AWS_288
  - CKV_AWS_23
  - CKV2_AWS_5
  - CKV2_AWS_61
  - CKV2_AWS_62
  - CKV2_AWS_6
  - CKV_AWS_18
  - CKV_AWS_145
  - CKV_AWS_144
  - CKV_AWS_21
  - CKV_AWS_152
  - CKV2_GHA_1
  - CKV_AWS_150
  - CKV2_AWS_28
