---
version: "3"

vars:
  IMAGE_REPO: sidpalas/devops-directive-docker-course-api-golang
  IMAGE_TAG: foobarbaz
  SERVICE_RELEASE_TAG: services/go/api-golang

tasks:

  build-container-image:
    desc: Build container image
    cmds:
      - |
        docker build \
          -t={{.IMAGE_TAG}} \
          .

  build-container-image-multi-arch:
    desc: Build multi-arch container image
    cmds:
      - |
        docker buildx build \
        --platform linux/amd64,linux/arm64 \
        -t {{.IMAGE_REPO}}:{{.IMAGE_TAG}} \
        --push \
        .

  test:
    desc: run tests
    cmds:
      - terraform plan --var-file="./envs/prd/terraform.tfvars"
